spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/big_data
    username: postgres
    password: postgres
server:
  servlet:
    context-path: /big_data
